on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest
    name: Run Check Dependencies Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Dependencies Action
        uses: ./
        with:
          apiKey: ${{ secrets.WEBSITE_ORACLE_API_KEY }}
          url: "https://cadmus-labs.github.io/"
          maxDepth: 1
          includeTypes: page,script,stylesheet

  trigger-on-external-repo:
    runs-on: ubuntu-latest
    name: Trigger on External Repo
    permissions:
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Trigger Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CADMUS_LABS_CICD_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cadmus-labs/cadmus-labs.github.io/actions/workflows/website-oracle-checks.yaml/dispatches \
            -d '{"ref":"main"}'
